name: Build Add-on Images

on:
  push:
    paths:
      - "hassio-ihost-silabs-multiprotocol/**"
      - "hassio-ihost-openthread-border-router/**"
      - "hassio-ihost-matter-server/**"
      - "hassio-ihost-esphome/**"
      - "hassio-ihost-node-red/**"
      - "hassio-ihost-ssh/**"
      - "hassio-ihost-ewelink-smart-home/**"
      - "hassio-ihost-ewelink-remote/**"
      - "hassio-ihost-sonoff-dongle-flasher/**"
      - "hassio-ihost-zigbee2mqtt/**"
      - "hassio-ihost-matter-bridge-addon/**"
      - "hassio-ihost-hardware-control/**"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.addon }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - addon: hassio-ihost-silabs-multiprotocol
            image: "hassio-ihost-silabs-multiprotocol-{arch}"
          - addon: hassio-ihost-openthread-border-router
            image: "openthread-border-router-{arch}"
          - addon: hassio-ihost-matter-server
            image: "hassio-ihost-matter-server-{arch}"
          - addon: hassio-ihost-esphome
            image: "esphome-hassio-{arch}"
          - addon: hassio-ihost-node-red
            image: "hassio-ihost-node-red-{arch}"
          - addon: hassio-ihost-ssh
            image: "hassio-ihost-ssh-{arch}"
          - addon: hassio-ihost-ewelink-smart-home
            image: "hassio-ihost-ewelink-smart-home-{arch}"
          - addon: hassio-ihost-ewelink-remote
            image: "hassio-ihost-ewelink-remote-{arch}"
          - addon: hassio-ihost-sonoff-dongle-flasher
            image: "hassio-ihost-sonoff-dongle-flasher-{arch}"
          - addon: hassio-ihost-zigbee2mqtt
            image: "hassio-ihost-zigbee2mqtt-{arch}"
          - addon: hassio-ihost-matter-bridge-addon
            image: "hassio-ihost-matter-bridge-{arch}"
          - addon: hassio-ihost-hardware-control
            image: "hassio-ihost-hardware-control-{arch}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.addon }}
        uses: home-assistant/builder@2024.03.5
        with:
          args: >-
            --all
            --target /data/${{ matrix.addon }}
            --image "${{ matrix.image }}"
            --docker-hub "ghcr.io/kije"
            --docker-hub-check
